2025-10-07 10:39:22 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:44:02 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:46:10 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:46:11 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 10:46:12 | CRITICAL | database.database_manager:__init__:23 - Konnte keine Verbindung zu Firestore herstellen: Project was not passed and could not be determined from the environment.
2025-10-07 10:46:13 | INFO     | __main__:main:9 - ==================================================
2025-10-07 10:46:13 | INFO     | __main__:main:10 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 10:46:13 | INFO     | __main__:main:11 - Blueprint Version: V7
2025-10-07 10:46:13 | INFO     | __main__:main:12 - ==================================================
2025-10-07 10:46:13 | INFO     | __main__:main:15 - Bot-Services werden initialisiert...
2025-10-07 10:46:13 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:57 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 10:46:13 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:62 - Abonnement-Bestätigung: {"jsonrpc":"2.0","result":3211930,"id":1}
2025-10-07 10:48:57 | INFO     | __main__:main:28 - Bot-Betrieb beendet.
2025-10-07 10:49:13 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:49:13 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 10:49:13 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 10:49:14 | INFO     | __main__:main:9 - ==================================================
2025-10-07 10:49:14 | INFO     | __main__:main:10 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 10:49:14 | INFO     | __main__:main:11 - Blueprint Version: V7
2025-10-07 10:49:14 | INFO     | __main__:main:12 - ==================================================
2025-10-07 10:49:14 | INFO     | __main__:main:15 - Bot-Services werden initialisiert...
2025-10-07 10:49:14 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:57 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 10:49:14 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:62 - Abonnement-Bestätigung: {"jsonrpc":"2.0","result":205824,"id":1}
2025-10-07 10:53:05 | INFO     | __main__:main:28 - Bot-Betrieb beendet.
2025-10-07 10:53:11 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:53:12 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 10:53:12 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 10:53:12 | INFO     | __main__:main:9 - ==================================================
2025-10-07 10:53:12 | INFO     | __main__:main:10 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 10:53:12 | INFO     | __main__:main:11 - Blueprint Version: V7
2025-10-07 10:53:12 | INFO     | __main__:main:12 - ==================================================
2025-10-07 10:53:12 | INFO     | __main__:main:15 - Bot-Services werden initialisiert...
2025-10-07 10:53:12 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:115 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 10:58:31 | INFO     | __main__:main:28 - Bot-Betrieb beendet.
2025-10-07 10:58:36 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 10:58:36 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 10:58:37 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 10:58:37 | INFO     | __main__:main:9 - ==================================================
2025-10-07 10:58:37 | INFO     | __main__:main:10 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 10:58:37 | INFO     | __main__:main:11 - Blueprint Version: V7
2025-10-07 10:58:37 | INFO     | __main__:main:12 - ==================================================
2025-10-07 10:58:37 | INFO     | __main__:main:15 - Bot-Services werden initialisiert...
2025-10-07 10:58:37 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 11:05:20 | INFO     | __main__:main:28 - Bot-Betrieb beendet.
2025-10-07 11:05:24 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 11:05:24 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 11:05:24 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 11:05:25 | INFO     | __main__:main:10 - ==================================================
2025-10-07 11:05:25 | INFO     | __main__:main:11 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 11:05:25 | INFO     | __main__:main:12 - Blueprint Version: V7
2025-10-07 11:05:25 | INFO     | __main__:main:13 - ==================================================
2025-10-07 11:05:25 | INFO     | __main__:main:16 - Bot-Services werden initialisiert...
2025-10-07 11:05:25 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:47 - Trigger Watcher Service gestartet.
2025-10-07 11:05:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:05:25 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 11:05:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:05:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:06:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:06:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:06:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:06:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:07:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:07:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:07:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:07:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:08:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:08:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:08:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:08:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:09:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:09:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:09:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:09:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:10:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:10:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:10:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:10:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:11:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:11:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:11:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:11:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:12:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:12:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:12:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:12:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:13:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:13:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:13:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:13:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:14:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:14:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:14:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:14:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:15:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:15:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:15:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:15:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:16:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:16:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:16:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:16:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:17:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:17:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:17:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:17:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:18:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:18:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:18:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:18:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:19:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:19:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:19:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:19:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:20:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:20:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:20:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:20:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:21:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:21:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:21:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:21:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:22:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:22:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:22:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:22:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:23:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:23:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:23:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:23:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:24:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:24:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:24:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:24:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:25:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:25:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:25:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:25:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:26:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:26:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:26:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:26:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:27:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:27:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:27:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:27:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:28:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:28:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:28:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:28:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:29:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:29:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:29:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:29:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:30:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:30:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:30:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:30:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:31:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:31:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:31:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:31:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:32:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:32:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:32:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:32:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:33:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:33:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:33:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:33:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:34:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:34:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:34:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:34:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:35:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:35:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:35:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:35:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:36:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:36:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:36:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:36:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:37:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:37:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:37:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:37:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:38:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:38:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:38:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:38:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:39:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:39:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:39:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:39:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:40:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:40:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:40:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:40:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:41:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:41:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:41:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:41:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:42:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:42:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:42:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:42:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:43:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:43:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:43:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:43:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:44:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:44:25 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:44:40 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:44:55 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 11:45:10 | ERROR    | database.database_manager:get_hot_watchlist:45 - Fehler beim Lesen der Hot Watchlist von Redis: Error Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
2025-10-07 12:34:53 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:34:58 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 12:35:03 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 12:35:04 | INFO     | __main__:main:10 - ==================================================
2025-10-07 12:35:04 | INFO     | __main__:main:11 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 12:35:04 | INFO     | __main__:main:12 - Blueprint Version: V7
2025-10-07 12:35:04 | INFO     | __main__:main:13 - ==================================================
2025-10-07 12:35:04 | INFO     | __main__:main:16 - Bot-Services werden initialisiert...
2025-10-07 12:35:04 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:47 - Trigger Watcher Service gestartet.
2025-10-07 12:35:04 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:182 - Ein kritischer Fehler im Gatekeeper-Service ist aufgetreten: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)
2025-10-07 12:35:14 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:182 - Ein kritischer Fehler im Gatekeeper-Service ist aufgetreten: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)
2025-10-07 12:35:24 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:182 - Ein kritischer Fehler im Gatekeeper-Service ist aufgetreten: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)
2025-10-07 12:35:26 | INFO     | __main__:main:30 - Bot-Betrieb beendet.
2025-10-07 12:35:50 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:35:50 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 12:35:50 | INFO     | database.database_manager:__init__:21 - Erfolgreich mit Firestore verbunden.
2025-10-07 12:35:50 | INFO     | __main__:main:10 - ==================================================
2025-10-07 12:35:50 | INFO     | __main__:main:11 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 12:35:50 | INFO     | __main__:main:12 - Blueprint Version: V7
2025-10-07 12:35:50 | INFO     | __main__:main:13 - ==================================================
2025-10-07 12:35:50 | INFO     | __main__:main:16 - Bot-Services werden initialisiert...
2025-10-07 12:35:50 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:47 - Trigger Watcher Service gestartet.
2025-10-07 12:35:51 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 12:46:03 | INFO     | __main__:main:30 - Bot-Betrieb beendet.
2025-10-07 12:46:45 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:48:33 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:48:33 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 12:48:34 | INFO     | database.database_manager:__init__:19 - Erfolgreich mit Firestore verbunden.
2025-10-07 12:50:13 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:50:14 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 12:50:14 | INFO     | database.database_manager:__init__:19 - Erfolgreich mit Firestore verbunden.
2025-10-07 12:50:14 | INFO     | __main__:main:11 - ==================================================
2025-10-07 12:50:14 | INFO     | __main__:main:12 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 12:50:14 | INFO     | __main__:main:13 - Blueprint Version: V7
2025-10-07 12:50:14 | INFO     | __main__:main:14 - ==================================================
2025-10-07 12:50:14 | INFO     | __main__:main:17 - Bot-Services werden initialisiert...
2025-10-07 12:50:14 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:48 - Trigger Watcher Service gestartet.
2025-10-07 12:50:14 | INFO     | bot_services.athena_engine:manage_positions:10 - Athena Engine (Positions-Manager) gestartet.
2025-10-07 12:50:15 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 12:50:15 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 12:52:15 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 12:54:15 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 12:54:32 | SUCCESS  | bot_services.gatekeeper_service:listen_for_new_pools:163 - Neuer Raydium Liquiditätspool entdeckt!
2025-10-07 12:56:15 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 12:58:15 | INFO     | __main__:main:31 - Bot-Betrieb beendet.
2025-10-07 12:58:19 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 12:58:19 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 12:58:20 | INFO     | database.database_manager:__init__:19 - Erfolgreich mit Firestore verbunden.
2025-10-07 12:58:20 | INFO     | __main__:main:11 - ==================================================
2025-10-07 12:58:20 | INFO     | __main__:main:12 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 12:58:20 | INFO     | __main__:main:13 - Blueprint Version: V7
2025-10-07 12:58:20 | INFO     | __main__:main:14 - ==================================================
2025-10-07 12:58:20 | INFO     | __main__:main:17 - Bot-Services werden initialisiert...
2025-10-07 12:58:20 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:48 - Trigger Watcher Service gestartet.
2025-10-07 12:58:20 | INFO     | bot_services.athena_engine:manage_positions:10 - Athena Engine (Positions-Manager) gestartet.
2025-10-07 12:58:20 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 12:58:20 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 13:00:20 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 13:01:37 | SUCCESS  | bot_services.gatekeeper_service:listen_for_new_pools:163 - Neuer Raydium Liquiditätspool entdeckt!
2025-10-07 13:02:20 | ERROR    | database.database_manager:get_open_positions:91 - Fehler beim Abrufen der Positionen von Firestore: 404 The database (default) does not exist for project chimera-trading-bot Please visit https://console.cloud.google.com/datastore/setup?project=chimera-trading-bot to add a Cloud Datastore or Cloud Firestore database. 
2025-10-07 13:03:57 | INFO     | __main__:main:31 - Bot-Betrieb beendet.
2025-10-07 13:04:11 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 13:04:11 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 13:04:12 | INFO     | database.database_manager:__init__:19 - Erfolgreich mit Firestore verbunden.
2025-10-07 13:04:12 | INFO     | __main__:main:11 - ==================================================
2025-10-07 13:04:12 | INFO     | __main__:main:12 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 13:04:12 | INFO     | __main__:main:13 - Blueprint Version: V7
2025-10-07 13:04:12 | INFO     | __main__:main:14 - ==================================================
2025-10-07 13:04:12 | INFO     | __main__:main:17 - Bot-Services werden initialisiert...
2025-10-07 13:04:12 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:48 - Trigger Watcher Service gestartet.
2025-10-07 13:04:12 | INFO     | bot_services.athena_engine:manage_positions:10 - Athena Engine (Positions-Manager) gestartet.
2025-10-07 13:04:12 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:155 - WebSocket-Verbindung zu QuickNode hergestellt. Lausche auf neue Pools...
2025-10-07 13:21:45 | INFO     | __main__:main:31 - Bot-Betrieb beendet.
2025-10-07 13:22:17 | INFO     | shared_utils.logging_setup:setup_logging:30 - Cerebrum (Logging-System) initialisiert.
2025-10-07 13:22:17 | INFO     | database.database_manager:__init__:11 - Erfolgreich mit Redis verbunden.
2025-10-07 13:22:18 | INFO     | database.database_manager:__init__:19 - Erfolgreich mit Firestore verbunden.
2025-10-07 13:22:18 | INFO     | __main__:main:11 - ==================================================
2025-10-07 13:22:18 | INFO     | __main__:main:12 - Starte den NonPlusUltra Trading Bot - Projekt Chimera
2025-10-07 13:22:18 | INFO     | __main__:main:13 - Blueprint Version: V7
2025-10-07 13:22:18 | INFO     | __main__:main:14 - ==================================================
2025-10-07 13:22:18 | INFO     | __main__:main:17 - Bot-Services werden initialisiert...
2025-10-07 13:22:18 | INFO     | bot_services.gatekeeper_service:listen_for_new_pools:121 - Gatekeeper startet im Polling-Modus...
2025-10-07 13:22:18 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:22:19 | INFO     | bot_services.trigger_watcher_service:watch_for_triggers:48 - Trigger Watcher Service gestartet.
2025-10-07 13:22:19 | INFO     | bot_services.athena_engine:manage_positions:10 - Athena Engine (Positions-Manager) gestartet.
2025-10-07 13:22:19 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:22:39 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:22:39 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:22:59 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:22:59 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:23:19 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:23:19 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:23:39 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:23:39 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:23:59 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:23:59 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:24:19 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:24:19 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
2025-10-07 13:24:39 | DEBUG    | bot_services.gatekeeper_service:listen_for_new_pools:125 - Suche nach neuen Pools...
2025-10-07 13:24:39 | CRITICAL | bot_services.gatekeeper_service:listen_for_new_pools:172 - Ein kritischer Fehler im Gatekeeper-Polling ist aufgetreten: 'solders.transaction_status.EncodedConfirmedTransactionWithStatusMeta' object has no attribute 'meta'
